---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox-sa-1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment-sa-1
  labels:
    app: busybox-sa-1
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox-sa-1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: busybox-sa-1
    spec:
      serviceAccountName: busybox-sa-1
      containers:
      - name: busybox
        image: yauritux/busybox-curl
        imagePullPolicy: IfNotPresent
        
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']