apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: author-default
  namespace: default
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/busybox-sa"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/ip"]